### ISSUE TITLE
updates fail?

### ISSUE THREAD

**Issue by breim9** [breim9/s-a#6]
section of code "HIGHLIGHT COLORS FROM DB TO JS " may cause problems?

When I attempted to update a separate plugin, stripe payments, it failed and the error message began with the script tags inside this section of code. 

Commenting out this section then let stripe payments update successfully.

**Comment by benreimer9** [comment]
note that highlightColor runs undefined if the php doesn't run first, and then crashes. Now handles highlightColor properly. 
Need to still test if this fixes it

**Comment by breim9** [comment]
potential solution can just be to make sure that code doesn't run on the plugins page (or even put in separate file and only call it on the correct pages)

**Comment by breim9** [comment]
issue #7 is resolved, this _should_ be resolved as well just waiting for actual confirmation
